#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --dpi 144
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
nitrogen --restore &
picom &
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape

bspc monitor -d dev www fm mus vid sys a b c ext

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config focused_border_color    '#523804'
bspc config normal_border_color     '#1d2021'

bspc rule -a Chromium   desktop=www  follow=on
bspc rule -a brave      desktop=www  follow=on
bspc rule -a firefox    desktop=www  follow=on

bspc rule -a dolphin    desktop=fm   follow=on
bspc rule -a pcmanfm    desktop=fm   follow=on

bspc rule -a keepassxc  desktop=sys  follow=on

bspc rule -a mpv        desktop=vid  follow=on state=floating
bspc rule -a mplayer2   desktop=vid  follow=on state=floating

bspc rule -a polybar    border=off manage=off
bspc rule -a Screenkey  manage=off
