#!/bin/bash
export QT_QPA_PLATFORMTHEME=gtk2
setxkbmap -option caps:escape
setxkbmap -option grp:alt_shift_toggle us,th
setxkbmap -option altwin:swap_alt_win
#xrandr --dpi 144
xsetroot -cursor_name left_ptr
xset s on
xset 480 120
xset r rate 300 40  # Auto key repeat rate
xkbset bouncekeys 35  # Debounce mechanical keyboard chatter
numlockx &

autorandr -c
if [[ "$(xrandr -q | grep -w connected -c)" == "1" ]]; then
    bspc monitor eDP-1 -d term www edit fm av sys a b c ext
else
    bspc monitor HDMI-1 -d term www edit fm a b
    bspc monitor eDP-1 -d sys x y av

    bpsc wm --reorder-monitors HDMI-1 eDP-1
fi

pgrep -x sxhkd > /dev/null || SXHKD_SHELL=/bin/zsh sxhkd &
[[ -x ~/.config/polybar/launch.sh ]] && ~/.config/polybar/launch.sh &
nitrogen --restore &
picom &
dunst &
xss-lock ~/.local/bin/lock-screen &
#pgrep -x redshift > /dev/null || redshift-gtk &
pgrep -x nm-applet > /dev/null || nm-applet &

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config focused_border_color    '#009191'
bspc config normal_border_color     '#1d2021'

# Bind browsers to www workspace
bspc rule -a Chromium       desktop=www  follow=on
bspc rule -a Google-chrome  desktop=www  follow=on
bspc rule -a Brave-browser  desktop=www  follow=on
bspc rule -a firefox        desktop=www  follow=on

# Bind file-managers to fm workspace
bspc rule -a dolphin        desktop=fm   follow=on
bspc rule -a Thunar         desktop=fm   follow=on
bspc rule -a Pcmanfm        desktop=fm   follow=on

# Bind editors to edit workspace
bspc rule -a Code           desktop=edit follow=on

# Bind media players to av workspace
bspc rule -a Spotify        desktop=av   follow=on
bspc rule -a mpv            desktop=av   follow=on state=floating
bspc rule -a mplayer2       desktop=av   follow=on state=floating

# sys workspace
bspc rule -a KeePassXC      desktop=sys  follow=on

# Floating window
bspc rule -a QjackCtl       state=floating
bspc rule -a qemu-system-x86_64 state=floating rectangle=1920x1080+1000+100

# Window manager exceptions
bspc rule -a polybar        border=off manage=off
bspc rule -a Dunst          border=off manage=off
bspc rule -a Screenkey      manage=off

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# sleep 10 && bpsc wm --reorder-monitors HDMI1 eDP1
